name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2  # This action logs in to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3  # This action builds and pushes the image
        with:
          push: true  # Set to false if you don't want to push
          tags: suprajaketha/appv1:latest
