name: .NET Core Desktop
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - Dev
        - PROD
        - QA
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:   
   - run: echo"me did the thing!"  
   
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}

           

                             
                             



