name: Copy Files
on:
  workflow_dispatch:
  

  push:
    paths:
      - '40_copy_file.bat'  # Path to your batch script file relative to the repository root
  pull_request:
    paths:
      - '40_copy_file.bat'  

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run batch script
        run: |
          ./40_copy_file.bat
