name: Backup Before Deploy

on:
    workflow_dispatch:
    push:
     branches:
      - master  # Adjust to match your main branch name

jobs:
  backup:
    runs-on: windows-latest  # Use the latest version of Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Backup Script
        run: |
         cd ${{ github.workspace }}
         ./Backup1.bat


      # You can add additional steps for deployment here
