name: Copy Files and Backup

on:
  workflow_dispatch: 
  push:
    paths:
      - '40_copy_file.bat'  
  pull_request:
    paths:
      - '40_copy_file.bat'  

jobs:
  copy-files-and-backup:
    runs-on: self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if backup folder exists
        run: |
          if (!(Test-Path 'C:\Users\Suparaja\Desktop\Batch script\Backup1')) {
            New-Item -ItemType Directory -Path 'C:\Users\Suparaja\Desktop\Batch script\Backup1'
          }

      - name: Create backup
        run: |
          xcopy /s /e /i * 'C:\Users\Suparaja\Desktop\Batch script\Backup1'

      - name: Run batch script
        run: |
          ./40_copy_file.bat
