name: Deployment Summary Report

on:
  push:
    branches:
      - dev

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: '7.x'  # Specify the version you want to use

      - name: Generate Deployment Summary Report
        run: |
          $ReportContent = @"
          Deployment Summary Report
          ========================
          Date: $(Get-Date)
          Application Name: MyApp
          Environment: Production
          Deployment Status: Success
          Deployed By: ${{ github.actor }}
          ========================
          "@
          Set-Content -Path deployment_summary.txt -Value $ReportContent
          Write-Output "Deployment summary report generated successfully."

      - name: Send Deployment Summary Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: Deployment Summary Report
          body: Please find the attached deployment summary report.
          to: kethasupraja@gmail.com
          attachments: deployment_summary.txt
