name: Send Deployment Summary Report

on:
  push:
    branches:
      - dev

jobs:
  send_report: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Deployment Summary
        run: |
          echo "Deployment Summary Report" > deployment_summary.txt
          echo "==========================" >> deployment_summary.txt
          echo "Date: $(date)" >> deployment_summary.txt
          echo "Application Name: MyApp" >> deployment_summary.txt
          echo "Environment: Production" >> deployment_summary.txt
          echo "Deployment Status: Success" >> deployment_summary.txt
          echo "Deployed By: $GITHUB_ACTOR" >> deployment_summary.txt
          echo "==========================" >> deployment_summary.txt

      - name: Send Deployment Summary Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: ${{ secrets.SMTP_USER }}
          to: kethasupraja@gmail.com
          subject: Deployment Summary Report
          body: Please find the attached deployment summary report.
          attachments: deployment_summary.txt
