name: Copy Files and Backup

on:
  workflow_dispatch: 
  push:
    paths:
      - '40_copy_file.bat'  
  pull_request:
    paths:
      - '40_copy_file.bat'  

jobs:
  copy-files-and-backup:
    runs-on: self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create backup folder
        run: |
          mkdir -p 'C:\Users\Suparaja\Desktop\Batch script\Backup1'
          cp -r * 'C:\Users\Suparaja\Desktop\Batch script\Backup1'  # Copy all files to the backup folder

      - name: Run batch script
        run: |
          ./40_copy_file.bat

 
