name: .NET Core Desktop
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - Dev
        - PROD
        - QA
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:   
   - run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
   
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}

 DEV:  

     #The type of runner that the job will run on 
     runs-on:  ubuntu-latest
     environment: DEV
 #steps represent a sequence of tast 
     steps:   
        
      - uses: actions/checkout@v2

        
      - name: Run a script
        run: |
         echo "I am running a job in the DEV environment"
 QA: 
     runs-on:  ubuntu-latest
     environment: QA
     needs: DEV

     steps:
     
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
         echo "I am running a job in the QA environment"

 PROD:
      runs-on:  ubuntu-latest
      environment: PROD
      needs: QA

      
      steps: 
      
       - uses: actions/checkout@v2

       - name: Run a script
         run: |
            echo "I am running a job in the PROD environment"           

                             
                             



