name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
     - name: Set up environment

       run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
   
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "boolean is ${{ inputs.boolean }}"
          echo "choice is ${{ inputs.choice }}"


 build_environment:
    name: Build on ${{ github.event.inputs.environment }} environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run selected action
        run: |
          environment=${{ github.event.inputs.environment }}
          if [ $environment = "BAR" ]; then
            echo "Hello, world!"
          elif [ $environment = "FOO" ]; then
            echo "I did the thing!"
          elif [ $environment = "REE" ]; then
            echo "This is the thing!"
          else
            echo "Invalid selection"
          fi
