name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
     - name: Set up environment

       run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
       
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "boolean is ${{ inputs.boolean }}"
 

 bar_environment:
    name: Build on BAR environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment != 'BAR' }}

    steps:
      - name: Pause job
        run: echo "Paused"
        
 foo_environment:
    name: Build on FOO environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment != 'FOO' }}

    steps:
      - name: Pause job
        run: echo "Paused"

 ree_environment:
    name: Build on REE environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment != 'REE' }}

    steps:
      - name: Pause job
        run: echo "Paused"

 selected_environment:
    name: Build on Selected Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'BAR' || github.event.inputs.environment == 'FOO' || github.event.inputs.environment == 'REE' }}

    steps:
      - name: Set up job
        run: echo "Set up job"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run selected option
        run: |
          case ${{ github.event.inputs.environment }} in
            BAR)
              echo "Hello, world!"
              ;;
            FOO)
              echo "I did the thing!"
              ;;
            REE)
              echo "This is the thing!"
              ;;
          esac

      - name: Post checkout repository
        run: echo "Post checkout repository"

      - name: Complete job
        run: echo "Complete job"         


