name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
     - name: Set up environment

       run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
       
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "boolean is ${{ inputs.boolean }}"
          echo "choice is ${{ inputs.choice }}"
 bar_environment:
    name: Build on BAR environment
    runs-on: ubuntu-latest

    steps:
      - name: Check selected environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" != "BAR" ]]; then
            echo "Paused"
            exit 1
          fi

      - name: Set up job
        if: github.event.inputs.environment == 'BAR'
        run: echo "Set up job"

      - name: Checkout repository
        if: github.event.inputs.environment == 'BAR'
        uses: actions/checkout@v2

      - name: Build on BAR environment
        if: github.event.inputs.environment == 'BAR'
        run: echo "Hello, world!"

      - name: Post checkout repository
        if: github.event.inputs.environment == 'BAR'
        run: echo "Post checkout repository"

      - name: Complete job
        if: github.event.inputs.environment == 'BAR'
        run: echo "Complete job"
 foo_environment:
    name: Build on FOO environment
    runs-on: ubuntu-latest

    steps:
      - name: Check selected environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" != "FOO" ]]; then
            echo "Paused"
            exit 1
          fi

      - name: Set up job
        if: github.event.inputs.environment == 'FOO'
        run: echo "Set up job"

      - name: Pause job
        run: echo "Paused"

 ree_environment:
    name: Build on REE environment
    runs-on: ubuntu-latest

    steps:
      - name: Check selected environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" != "REE" ]]; then
            echo "Paused"
            exit 1
          fi

      - name: Set up job
        if: github.event.inputs.environment == 'REE'
        run: echo "Set up job"

      - name: Pause job
        run: echo "Paused"


      

     
            
 
     
   
