name: Run Selected Option

on:
  workflow_dispatch:
    inputs:
     choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE

     dropdown_option:
        description: 'Select the environment'
        required: true
        options: ['BAR', 'FOO', 'REE']




jobs:
  run_selected_option:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run selected option
        if: ${{ github.event.inputs.dropdown_option == 'BAR' }}
        run: |
          echo "hello world!"

      - name: Run selected option
        if: ${{ github.event.inputs.dropdown_option == 'FOO' }}
        run: |
          echo "I did the thing!"

      - name: Run selected option
        if: ${{ github.event.inputs.dropdown_option == 'REE' }}
        run: |
          echo "This is the thing!"

