name: Basicworkflow Dispatch Example


on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        description: 'Select an option'
        required: true
        default: 'BAR'
        options: ['BAR', 'FOO', 'REE']

jobs:
  run_selected_option:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run selected option
        run: |
          case ${{ github.event.inputs.dropdown_option }} in
            "BAR")
              echo "hello world!"
              ;;
            "FOO")
              echo "I did the thing!"
              ;;
            "REE")
              echo "This is the thing!"
              ;;
          esac
      
      - name: Pause other options
        if: ${{ github.event.inputs.dropdown_option != 'BAR' }}
        run: echo "Option BAR paused"
      
      - name: Pause other options
        if: ${{ github.event.inputs.dropdown_option != 'FOO' }}
        run: echo "Option FOO paused"
      
      - name: Pause other options
        if: ${{ github.event.inputs.dropdown_option != 'REE' }}
        run: echo "Option REE paused"
