name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
     - name: Set up environment

       run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
   
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "boolean is ${{ inputs.boolean }}"
          echo "choice is ${{ inputs.choice }}"
 test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          if [ "${{ inputs.choice }}" = "bar" ]; then
            echo "Hello, world!"
          elif [ "${{ inputs.choice }}" = "foo" ]; then
            echo "I did the thing!"
          elif [ "${{ inputs.choice }}" = "ree" ]; then
            echo "This is the thing!"
          else
            echo "Unknown choice: ${{ inputs.choice }}"
          fi
       
          
