name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE

    
      environment: 
        required: true
        default: 'BAR'  # Default environment

jobs:
  bar_environment:
    name: Build on BAR environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'BAR' }}

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on BAR environment
        run: echo "Hello, world!"

      - name: Post checkout repository
        run: echo "Post checkout repository"

     
        
  foo_environment:
    name: Build on FOO environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'FOO' }}

    steps:

      - name: Build on FOO environment
        run: echo "I did the Thing!"
      
      - name: Pause job
        run: echo "Paused"
        
  ree_environment:
    name: Build on REE environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'REE' }}

    steps:

     - name: Build on REE environmnet
       run: echo "This is the Thing!"
       
     - name: Pause job
       run: echo "Paused"
       
