name: Basicworkflow Dispatch Example
on:
  workflow_dispatch: 
   inputs:
      choice:
        type: choice
        description: select the environment
        options:
        - BAR
        - FOO
        - REE
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
     - name: Set up environment

       run:  echo "Selected environment is ${{ github.event.inputs.environment }}"  
       
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "boolean is ${{ inputs.boolean }}"
          echo "choice is ${ { inputs.choice }}"


 bar_environment:
    name: Build on BAR environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'BAR' }}

    steps:
      - name: Set up job
        run: echo "Set up job"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on BAR environment
        run: echo "Hello, world!"

      - name: Post checkout repository
        run: echo "Post checkout repository"

      - name: Complete job
        run: echo "Complete job"
        
 foo_environment:
    name: Build on FOO environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'FOO' }}

    steps:
      - name: Set up job
        run: echo "Set up job"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on FOO environment
        run: echo "I did the thing!"

      - name: Post checkout repository
        run: echo "Post checkout repository"

      - name: Complete job
        run: echo "Complete job"

 ree_environment:
    name: Build on REE environment
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'REE' }}

    steps:
      - name: Set up job
        run: echo "Set up job"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on REE environment
        run: echo "This is the thing!"

      - name: Post checkout repository
        run: echo "Post checkout repository"

      - name: Complete job
        run: echo "Complete job"
