name: Basicworkflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        options: ['DEV', 'QA', 'PROD']
   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Selected environment is ${{ github.event.inputs.environment }}"

  DEV:  

     #The type of runner that the job will run on 
     runs-on:  ubuntu-latest
     environment: DEV
 #steps represent a sequence of tast 
     steps:   
        
      - uses: actions/checkout@v2

        
      - name: Run a script
        run: |
         echo "I am running a job in the DEV environment"

  QA: 
     runs-on:  ubuntu-latest
     environment: QA
     needs: DEV

     steps:
     
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
         echo "I am running a job in the QA environment"

  PROD:
      runs-on:  ubuntu-latest
      environment: PROD
      needs: QA

      
      steps: 
      
       - uses: actions/checkout@v2

       - name: Run a script
         run: |
            echo "I am running a job in the PROD environment"
 
