name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Check if folder exists to download artifacts
      - name: Check if folder exists
        run: |
          if [ -d "my_artifacts" ]; then
            echo "Folder 'my_artifacts' exists."
          else
            echo "Folder 'my_artifacts' does not exist. Creating folder..."
            mkdir -p my_artifacts
          fi

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Downloading artifacts to folder 'my_artifacts'..."
          
