
name: Run Selected Option

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  run_selected_option:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-dotnet-app:latest .

      - name: Run Docker container
        run: |
          docker run --name my-dotnet-container -v C:\Users\Suparaja\Desktop\myartifacts:/app/myartifacts my-dotnet-app:latest

      - name: Copy artifacts
        run: |
          docker cp my-dotnet-container:/app/publish_output C:\Users\Suparaja\Desktop\myartifacts

      - name: Clean up
        run: |
          docker rm my-dotnet-container
          docker rmi my-dotnet-app:latest
