name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build and publish the project
      - name: Build and publish
        run: |
          dotnet build StudentManagementSystem.csproj
          dotnet publish StudentManagementSystem.csproj -c Release -o publish_output
          
      # Create a folder if it doesn't exist
      - name: Create artifacts folder
        run: mkdir -p C:/Users/Suparaja/Desktop/my_artifacts

      # Publish artifacts if folder exists
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: project-artifacts
          path: publish_output

      # Download artifacts to specified local directory
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/download-artifact@v2
        with:
          name: project-artifacts
          path: C:/Users/Suparaja/Desktop/my_artifacts
