name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Check if folder exists to download artifacts and create if not
      - name: Check and create artifacts folder
        run: |
          if (-Not (Test-Path -Path "my_artifacts" -PathType Container)) {
            Write-Output "Folder 'my_artifacts' does not exist. Creating folder..."
            New-Item -ItemType Directory -Path "my_artifacts"
          } else {
            Write-Output "Folder 'my_artifacts' exists."
          }

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          Write-Output "Downloading artifacts to folder 'my_artifacts'..."
          
