name: Dispatch Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'pro' # Default to pro environment if not specified

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        id: env
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_PAT }}
          script: |
            const { data } = await github.request('GET /repos/{owner}/{repo}/environments');
            const envs = data.environments;
            const proEnv = envs.find(env => env.name === 'pro');
            const stageEnv = envs.find(env => env.name === 'stage');
            const comEnv = envs.find(env => env.name === 'com');
            return {
              pro: proEnv,
              stage: stageEnv,
              com: comEnv
            };

      - name: Deploy to Pro
        if: ${{ github.event.inputs.environment == 'pro' && steps.env.outputs.pro }}
        run: |
          echo "Hey, this is pro."
          # Add deployment steps for pro environment here

      - name: Deploy to Stage
        if: ${{ github.event.inputs.environment == 'stage' && steps.env.outputs.stage }}
        run: |
          echo "Hey, this is stage."
          # Add deployment steps for stage environment here

      - name: Deploy to Com
        if: ${{ github.event.inputs.environment == 'com' && steps.env.outputs.com }}
        run: |
          echo "Hey, this is com."
          # Add deployment steps for com environment here
