name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create a folder to save artifacts
      - name: Create artifacts folder
        run: New-Item -ItemType Directory -Path "C:\Users\Supraja\my_artifacts"

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          Write-Output "Downloading artifacts to folder..."
          
