name: Run Selected Option

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE
           

jobs:
  run_selected_option:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run selected option (BAR)
        if: ${{ github.event.inputs.dropdown_option == 'BAR' }}
        run: |
         dotnet build StudentManagementSystem.csproj  

      - name: Run selected option (FOO)
        if: ${{ github.event.inputs.dropdown_option == 'FOO' }}
        run: |
         dotnet build StudentManagementSystem.csproj  

      - name: Run selected option (REE)
        if: ${{ github.event.inputs.dropdown_option == 'REE' }}
        run: |
         dotnet build StudentManagementSystem.csproj 
         
      - name: upload Artifacts
        run: mkdir staging && cp target/*.jar staging
    
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: package
          path: staging
       
     
