name: Dispatch and Scheduled Pipeline

on:
  schedule:
    - cron: '5 7 * * *' # This will trigger the workflow every day at 07:05 AM UTC (which is 12:35 PM IST)

jobs:
  timed-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' && github.event.schedule == 'cron(5 7 * * *)' && github.ref == 'refs/heads/dev' }}
    steps:
      - name: Set up time variables
        id: time
        run: |
          export TZ=Asia/Kolkata
          current_time=$(date +"%H:%M")
          echo "current_time=$current_time" >> $GITHUB_ENV
          scheduled_time="13:05"
          echo "scheduled_time=$scheduled_time" >> $GITHUB_ENV

      - name: Check if triggered at the correct time
        run: |
          if [ "$current_time" == "$scheduled_time" ]; then
            echo "The job is running at the scheduled time: $scheduled_time IST"
          else
            echo "The job was manually triggered or is not running at the scheduled time. Scheduled time is $scheduled_time IST, current time is $current_time IST"
          fi
        env:
          current_time: ${{ env.current_time }}
          scheduled_time: ${{ env.scheduled_time }}

      - name: Execute pipeline task
        run: |
          # Use GitHub API to check if conditions (approvals, time delays) for the "pro" environment are met
          # Example using GitHub Script:
          # https://docs.github.com/en/rest/reference/repos#get-environment
          # echo "::set-output name=conditions_met::true"
          shell: /usr/bin/bash -e {0}
