name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create a folder to save artifacts
      - name: Create artifacts folder
        run: mkdir -p my_artifacts

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p my_artifacts
          echo "Downloading artifacts to folder..."
          curl -L -o my_artifacts/artifacts.zip ${{ github.event.workflow_run.artifacts_url }}
          unzip my_artifacts/artifacts.zip -d my_artifacts
