name: Run Selected Option

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  run_selected_option:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run selected option
        run: |
          dotnet build StudentManagementSystem.csproj
          dotnet publish StudentManagementSystem.csproj -c Release -o publish_output

      - name: Check if folder exists
        id: check_folder
        run: |
          if [ -d "project-artifacts" ]; then
            echo "Folder exists"
            echo "::set-output name=folder_exists::true"
          else
            echo "Folder does not exist"
            echo "::set-output name=folder_exists::false"
          fi

      - name: Publish Artifacts
        if: steps.check_folder.outputs.folder_exists == 'true'
        uses: actions/upload-artifact@v2.2.0
        with:
          name: project-artifacts
          path: publish_output

      - name: Publish Artifacts without folder
        if: steps.check_folder.outputs.folder_exists == 'false'
        uses: actions/upload-artifact@v2.2.0
        with:
          name: project-artifacts
          path: publish_output/*
