name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create a folder with timestamp for artifacts
      - name: Create artifacts folder
        run: |
          mkdir -p my_artifacts/$(date +'%Y-%m-%d_%H-%M-%S')
          echo "Created artifacts folder with name: $(date +'%Y-%m-%d_%H-%M-%S')"

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Downloading artifacts to folder..."
         
