name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      dropdown_option:
        type: choice
        description: Select the Environment
        options:
          - BAR
          - FOO
          - REE

jobs:
  download_artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create a folder to save artifacts if it doesn't exist
      - name: Create artifacts folder
        run: |
          if [ ! -d "my_artifacts" ]; then
            mkdir -p my_artifacts
          else
            echo "Folder 'my_artifacts' already exists."
          fi

      # Download artifacts to the specified folder
      - name: Download Artifacts
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Downloading artifacts to folder..."
         
