name: Build and Restart AnyDesk Service

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Batch Script
      shell: cmd
      run: |
        curl -o service.bat https://raw.githubusercontent.com/Suprajaketha/student-management-system/dev/service.bat
        .\service.bat
