name: Local Service Management Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stop-service-and-build:
    name: Stop Service and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Stop Service and Build
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.1.177  
          username: suprajaketha 
          password: supraja8  
          script: |
            # Stop the AnyDesk service
            taskkill /F /IM AnyDesk.exe
            
            # Perform the build process here (e.g., npm install, npm build, etc.)
            run:|
            Backup1.bat
            
            # Restart the AnyDesk service
            "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
