name: AnyDesk Service

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
        
    steps:
    - name: Run Batch Script
      run: |
         https://github.com/Suprajaketha/student-management-system/blob/dev/service.bat
