name: AnyDesk Service

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
        
    steps:
    - name: Run Batch Script
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Suprajaketha/student-management-system/dev/service.bat" -OutFile "service.bat"
        cmd /c service.bat
