name: AnyDesk Service

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    
    
    steps:
    - name: Run Batch Script
      run: |
        curl -sS https://raw.githubusercontent.com/Suprajaketha/student-management-system/dev/service.bat | cmd
