name: Scheduled Pipeline (Dev Branch)

on:
  schedule:
    - cron: '40 13 * * *'  # Runs at 13:40 IST every day

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust as needed
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository
      - name: Select Branch
        run: git checkout dev  # Switch to dev branch
      - name: Install Dependencies (if applicable)
        run: |
          npm install  # Example for npm packages
          # Or
          pip install  # Example for pip packages
      - name: Run Tests (if applicable)
        run: |
          npm test  # Example for npm scripts
          # Or
          pytest  # Example for pytest
      - name: Build (if applicable)
        run: |
          npm run build  # Example for npm scripts
          # Or
          make build  # Example for makefile
#123
