name: Dispatch and Scheduled Pipeline

on:
  workflow_dispatch:
    inputs:
      scheduled_time:
        description: 'Scheduled Time in IST (HH:MM format)'
        required: true
        default: '13:17'

jobs:
  timed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time variables
        id: time
        run: |
          export TZ=Asia/Kolkata
          current_time=$(date +"%H:%M")
          echo "current_time=$current_time" >> $GITHUB_ENV
          scheduled_time="${{ github.event.inputs.scheduled_time }}"
          echo "scheduled_time=$scheduled_time" >> $GITHUB_ENV

      - name: Check if triggered at the correct time
        run: |
          if [ "$current_time" == "$scheduled_time" ]; then
            echo "The job is running at the scheduled time: $scheduled_time IST"
          else
            echo "The job was manually triggered or is not running at the scheduled time. Scheduled time is $scheduled_time IST, current time is $current_time IST"
          fi
        env:
          current_time: ${{ env.current_time }}
          scheduled_time: ${{ env.scheduled_time }}

      - name: Execute pipeline task
        run: |
          # Use GitHub API to check if conditions (approvals, time delays) for the "pro" environment are met
          # Example using GitHub Script:
          # https://docs.github.com/en/rest/reference/repos#get-environment
          # echo "::set-output name=conditions_met::true"
          /usr/bin/bash -e -c "/usr/bin/bash -e {0}"
