name: Scheduled and Manual Pipeline

on:
  schedule:
    - cron: '0 8 * * *' # This will trigger the workflow every day at 8:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  timed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggered at the correct time
        run: |
          current_time=$(date -u +"%H:%M")
          scheduled_time="08:00"
          if [ "$current_time" == "$scheduled_time" ]; then
            echo "The job is running at the scheduled time: $scheduled_time UTC"
          else
            echo "The job was manually triggered or is not running at the scheduled time. Scheduled time is $scheduled_time UTC, current time is $current_time UTC"
          fi

      - name: Execute pipeline task
        run: echo "Executing the pipeline task..."   
