name: Scheduled Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '22 7 * * *' # This will trigger the workflow every day at 07:22 AM UTC (which is 12:52 PM IST)

jobs:
  timed-job:
    if: github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Set up time variables
        id: time
        run: |
          export TZ=Asia/Kolkata
          current_time=$(date +"%H:%M")
          echo "current_time=$current_time" >> $GITHUB_ENV
          scheduled_time="12:52"
          echo "scheduled_time=$scheduled_time" >> $GITHUB_ENV

      - name: Check if triggered at the correct time
        run: |
          if [ "$current_time" == "$scheduled_time" ]; then
            echo "The job is running at the scheduled time: $scheduled_time IST"
          else
            echo "The job was manually triggered or is not running at the scheduled time. Scheduled time is $scheduled_time IST, current time is $current_time IST"
          fi
        env:
          current_time: ${{ env.current_time }}
          scheduled_time: ${{ env.scheduled_time }}

      - name: Execute pipeline task
        run: echo "Executing the pipeline task..."
